using Microsoft.CodeAnalysis;

namespace Nkraft.MvvmEssentials.SourceGenerator;

internal static class AppStartupCodeTemplates
{
    public static string UserStartupRegistration(INamedTypeSymbol startup)
    {
        var fullName = startup.ToDisplayString();
        return $$"""
            // <auto-generated/>
            // Detected user-defined IAppStartup: {{fullName}}
            #nullable enable

            using Microsoft.Extensions.DependencyInjection;
            using Nkraft.MvvmEssentials.Services;

            namespace Nkraft.MvvmEssentials;

            internal static class AppStartupRegistrationExtensions
            {
                internal static IServiceCollection AddDiscoveredAppStartup(this IServiceCollection services)
                {
                    services.AddTransient<IAppStartup, global::{{fullName}}>();
                    return services;
                }
            }
            """;
    }

    public static string DefaultStartup(string initialViewModelFullName)
    {
        return $$"""
            // <auto-generated/>
            // Default IAppStartup generated from MapPage<_, {{initialViewModelFullName}}>(isInitial: true)
            #nullable enable

            using System.Threading.Tasks;
            using Nkraft.MvvmEssentials;
            using Nkraft.MvvmEssentials.Services;

            namespace Nkraft.MvvmEssentials;

            internal sealed class GeneratedAppStartup(INavigationService navigationService) : IAppStartup
            {
                private readonly INavigationService _navigationService = navigationService;

                async Task IAppStartup.OnInitializedAsync()
                {
                    await _navigationService
                        .Absolute(withNavigation: false)
                        .Push<global::{{initialViewModelFullName}}>()
                        .NavigateAsync(animated: false);
                }
            }
            """;
    }

    public static string DefaultStartupRegistration()
    {
        return """
            // <auto-generated/>
            #nullable enable

            using Microsoft.Extensions.DependencyInjection;
            using Nkraft.MvvmEssentials.Services;

            namespace Nkraft.MvvmEssentials;

            internal static class AppStartupRegistrationExtensions
            {
                internal static IServiceCollection AddDiscoveredAppStartup(this IServiceCollection services)
                {
                    services.AddTransient<IAppStartup, GeneratedAppStartup>();
                    return services;
                }
            }
            """;
    }

    public static string NoOpRegistration()
    {
        return """
            // <auto-generated/>
            #nullable enable

            using Microsoft.Extensions.DependencyInjection;

            namespace Nkraft.MvvmEssentials;

            internal static class AppStartupRegistrationExtensions
            {
                internal static IServiceCollection AddDiscoveredAppStartup(this IServiceCollection services)
                    => services; // MVE001: no startup defined
            }
            """;
    }
}