using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using Microsoft.CodeAnalysis;
using Microsoft.CodeAnalysis.CSharp;
using Microsoft.CodeAnalysis.CSharp.Syntax;

namespace Nkraft.MvvmEssentials.SourceGenerator;

// per-property (your type, now a record so it has value equality for the incremental cache)
public sealed record ViewModelParameters(string PropertyName, string PropertyType, bool IsRequired);

// per-VM — this is what was missing: carries where to emit
internal sealed record ViewModelTarget(string Namespace, string ClassName, EquatableArray<ViewModelParameters> Parameters);

[Generator]
public class NavigationParametersGenerator : IIncrementalGenerator
{
    private const string NavigableViewModelName  = "Nkraft.MvvmEssentials.ViewModels.NavigableEntryViewModel";
    private const string NavigationParameterName = "Nkraft.MvvmEssentials.Attributes.ParameterAttribute";

    void IIncrementalGenerator.Initialize(IncrementalGeneratorInitializationContext context)
    {
        var targets = context.SyntaxProvider.CreateSyntaxProvider(
                predicate: static (node, _) => ClassPropertiesHasAttributes(node),
                transform: static (ctx, _) => ToViewModelTarget(ctx))
            .Where(static t => t is not null)
            .Select(static (t, _) => t!);

        context.RegisterSourceOutput(targets, static (spc, t) => Emit(spc, t));
    }

    private static bool ClassPropertiesHasAttributes(SyntaxNode node) =>
        node is ClassDeclarationSyntax cls &&
        cls.Members.OfType<PropertyDeclarationSyntax>().Any(p => p.AttributeLists.Count > 0);

    private static ViewModelTarget? ToViewModelTarget(GeneratorSyntaxContext ctx)
    {
        var classDecl = (ClassDeclarationSyntax)ctx.Node;
        if (ctx.SemanticModel.GetDeclaredSymbol(classDecl) is not INamedTypeSymbol symbol)
            return null;
        if (IsDerivedFrom(symbol, NavigableViewModelName) == false)
            return null;

        var props = symbol.GetMembers()
            .OfType<IPropertySymbol>()
            .Where(p => p.GetAttributes().Any(a => a.AttributeClass?.ToDisplayString() == NavigationParameterName))
            .Select(p =>
            {
                var attr = p.GetAttributes().First(a => a.AttributeClass?.ToDisplayString() == NavigationParameterName);
                // absent → required by default; opt out with [Parameter(IsRequired = false)]
                var isRequired = attr.NamedArguments.FirstOrDefault(na => na.Key == "IsRequired").Value.Value as bool? ?? true;
                return new ViewModelParameters(
                    p.Name,
                    p.Type.ToDisplayString(SymbolDisplayFormat.FullyQualifiedFormat), // global:: → no resolution surprises
                    isRequired);
            })
            .ToArray();

        if (props.Length == 0)
            return null;

        var ns = symbol.ContainingNamespace.IsGlobalNamespace
            ? string.Empty
            : symbol.ContainingNamespace.ToDisplayString();

        return new ViewModelTarget(ns, symbol.Name, new EquatableArray<ViewModelParameters>(props));
    }

    private static void Emit(SourceProductionContext spc, ViewModelTarget t)
    {
        var sb = new StringBuilder();
        sb.AppendLine("// <auto-generated/>");
        sb.AppendLine("#nullable enable");
        if (t.Namespace.Length > 0)
            sb.Append("namespace ").Append(t.Namespace).AppendLine(";").AppendLine();

        sb.Append("partial class ").AppendLine(t.ClassName);
        sb.AppendLine("{");

        sb.Append("    public sealed record Parameters : global::Nkraft.MvvmEssentials.INavigationTarget<")
          .Append(t.ClassName).AppendLine(">");
        sb.AppendLine("    {");
        foreach (var p in t.Parameters.Array)
        {
            sb.Append("        public ");
            if (p.IsRequired) sb.Append("required ");
            sb.Append(p.PropertyType).Append(' ').Append(p.PropertyName).AppendLine(" { get; init; }");
        }
        sb.AppendLine();
        sb.AppendLine("        public global::Nkraft.MvvmEssentials.Services.INavigationParameters ToNavigationParameters()");
        sb.AppendLine("        {");
        sb.AppendLine("            var __p = new global::Nkraft.MvvmEssentials.Services.NavigationParameters();");
        foreach (var p in t.Parameters.Array)
            sb.Append("            __p.Add(\"").Append(p.PropertyName).Append("\", ").Append(p.PropertyName).AppendLine(");");
        sb.AppendLine("            return __p;");
        sb.AppendLine("        }");
        sb.AppendLine("    }");
        sb.AppendLine();

        sb.AppendLine("    protected internal override void ApplyNavigationParameters(global::Nkraft.MvvmEssentials.Services.INavigationParameters parameters)");
        sb.AppendLine("    {");
        var i = 0;
        foreach (var p in t.Parameters.Array)
        {
            var v = "__v" + i++;
            sb.Append("        if (parameters.TryGetValue<").Append(p.PropertyType).Append(">(\"")
              .Append(p.PropertyName).Append("\", out var ").Append(v).Append(")) this.")
              .Append(p.PropertyName).Append(" = ").Append(v).AppendLine("!;");
        }
        sb.AppendLine("    }");

        sb.AppendLine("}");

        var hint = (t.Namespace.Length > 0 ? t.Namespace + "." : string.Empty) + t.ClassName + ".NavigationParameters.g.cs";
        spc.AddSource(hint, sb.ToString());
    }

    private static bool IsDerivedFrom(INamedTypeSymbol symbol, string baseTypeName)
    {
        for (var t = symbol; t is not null; t = t.BaseType)
            if (t.ToDisplayString() == baseTypeName)
                return true;
        return false;
    }
}

// arrays don't have structural equality, which silently breaks incremental caching.
// this wrapper restores it so the pipeline actually memoizes per-VM.
internal readonly struct EquatableArray<T>(T[] array) : IEquatable<EquatableArray<T>> where T : IEquatable<T>
{
    public readonly T[] Array = array;

    public bool Equals(EquatableArray<T> other)
    {
        if (Array is null) return false;
        if (Array.Length != other.Array.Length) return false;
        return Array.Where((t, i) => !t.Equals(other.Array[i])).Any() == false;
    }

    public override bool Equals(object? obj) => obj is EquatableArray<T> o && Equals(o);

    public override int GetHashCode()
    {
        if (Array is null) return 0;
        unchecked
        {
            return Array.Aggregate(17, (current, item) => current * 31 + item.GetHashCode());
        }
    }
}