using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using Microsoft.CodeAnalysis;
using Microsoft.CodeAnalysis.CSharp;

namespace Nkraft.MvvmEssentials.SourceGenerator;

internal sealed record ViewModelParameter(
    string PropertyName,
    string Type,
    bool IsRequired);

internal sealed record ViewModelTarget(
    string Namespace,
    string ClassName,
    string Accessibility,
    EquatableArray<ViewModelParameter> Parameters);

[Generator]
public sealed class NavigationParametersGenerator : IIncrementalGenerator
{
    private const string NavigableViewModelName  = "Nkraft.MvvmEssentials.ViewModels.NavigableEntryViewModel";
    private const string NavigationParameterName = "Nkraft.MvvmEssentials.Attributes.NavigationParameterAttribute";

    private static readonly SymbolDisplayFormat TypeFormat =
        SymbolDisplayFormat.FullyQualifiedFormat.AddMiscellaneousOptions(
            SymbolDisplayMiscellaneousOptions.IncludeNullableReferenceTypeModifier);

    void IIncrementalGenerator.Initialize(IncrementalGeneratorInitializationContext context)
    {
        var targets = context.SyntaxProvider.ForAttributeWithMetadataName(
                NavigationParameterName,
                predicate: static (node, _) => node.IsKind(SyntaxKind.PropertyDeclaration),
                transform: static (ctx, _) => ToViewModelTarget(ctx.TargetSymbol.ContainingType))
            .Where(static t => t is not null)
            .Select(static (t, _) => t!)
            .Collect();

        context.RegisterSourceOutput(targets, static (spc, all) =>
        {
            // one attributed property -> one pipeline item, so the same VM appears N times
            foreach (var t in all.Distinct())
                Emit(spc, t);
        });
    }

    private static ViewModelTarget? ToViewModelTarget(INamedTypeSymbol? symbol)
    {
        if (symbol is null)
            return null;

        // skip framework bases, generic and nested VMs — none of these can host a valid partial emit
        if (symbol.IsAbstract || symbol.IsStatic || symbol.IsGenericType || symbol.ContainingType is not null)
            return null;

        if (IsDerivedFrom(symbol, NavigableViewModelName) == false)
            return null;

        var props = CollectParameters(symbol);
        if (props.Length == 0)
            return null;

        var ns = symbol.ContainingNamespace.IsGlobalNamespace
            ? string.Empty
            : symbol.ContainingNamespace.ToDisplayString();

        return new ViewModelTarget(
            ns,
            symbol.Name,
            ToKeyword(symbol.DeclaredAccessibility),
            new EquatableArray<ViewModelParameter>(props));
    }

    private static ViewModelParameter[] CollectParameters(INamedTypeSymbol symbol)
    {
        var result = new List<ViewModelParameter>();
        var names = new HashSet<string>(StringComparer.Ordinal);

        // walk the hierarchy so parameters declared on an intermediate VM are included;
        // most-derived wins on name collision
        for (var t = symbol; t is not null; t = t.BaseType)
        {
            if (t.ToDisplayString() == NavigableViewModelName)
                break;

            foreach (var p in t.GetMembers().OfType<IPropertySymbol>())
            {
                var attr = p.GetAttributes()
                    .FirstOrDefault(a => a.AttributeClass?.ToDisplayString() == NavigationParameterName);
                if (attr is null || names.Add(p.Name) == false)
                    continue;

                var isRequired = attr.NamedArguments
                    .FirstOrDefault(na => na.Key == "IsRequired").Value.Value as bool? ?? true;
                
                result.Add(new ViewModelParameter(
                    PropertyName: p.Name,
                    Type: p.Type.ToDisplayString(TypeFormat),
                    IsRequired: isRequired));
            }
        }

        // required first (C# demands optionals last); OrderBy is stable, so declaration order holds within each group
        return result.OrderByDescending(p => p.IsRequired).ToArray();
    }

    private static void Emit(SourceProductionContext spc, ViewModelTarget t)
    {
        var sb = new StringBuilder();
        sb.AppendLine("// <auto-generated/>");
        sb.AppendLine("#nullable enable");
        if (t.Namespace.Length > 0)
            sb.Append("namespace ").Append(t.Namespace).AppendLine(";").AppendLine();

        sb.Append(t.Accessibility).Append(" partial class ").AppendLine(t.ClassName);
        sb.AppendLine("{");

        sb.Append("    public static global::Nkraft.MvvmEssentials.Services.Pages.PageDestination With(");
        sb.Append(string.Join(", ", t.Parameters.Array.Select(p => p.IsRequired
            ? $"{p.Type} {ToParameterName(p.PropertyName)}"
            : $"{ToNullable(p.Type)} {ToParameterName(p.PropertyName)} = default")));
        sb.AppendLine(")");
        sb.AppendLine("    {");
        sb.AppendLine("        var __p = new global::Nkraft.MvvmEssentials.Services.NavigationParameters();");

        foreach (var p in t.Parameters.Array)
        {
            var name = ToParameterName(p.PropertyName);
            if (p.IsRequired)
                sb.Append("        __p.Add(\"").Append(p.PropertyName).Append("\", ").Append(name).AppendLine(");");
            else
                sb.Append("        if (").Append(name).Append(" is not null) __p.Add(\"")
                    .Append(p.PropertyName).Append("\", ").Append(name).AppendLine(");");
        }
        
        var pageName = t.ClassName.Replace("ViewModel", "Page");
        sb.AppendLine($"        return new global::Nkraft.MvvmEssentials.Services.Pages.PageDestination(\"{pageName}\", __p);");
        sb.AppendLine("    }");
        sb.AppendLine("}");

        var hint = (t.Namespace.Length > 0 ? t.Namespace + "." : string.Empty) + t.ClassName + ".NavigationParameters.g.cs";
        spc.AddSource(hint, sb.ToString());
    }

    private static bool IsDerivedFrom(INamedTypeSymbol symbol, string baseTypeName)
    {
        for (var t = symbol.BaseType; t is not null; t = t.BaseType)
            if (t.ToDisplayString() == baseTypeName)
                return true;
        return false;
    }
    
    private static string ToNullable(string type) =>
        type.EndsWith("?", StringComparison.Ordinal) ? type : type + "?";

    private static string ToKeyword(Accessibility accessibility) => accessibility switch
    {
        Accessibility.Public => "public",
        Accessibility.Internal => "internal",
        _ => "internal"
    };

    private static string ToParameterName(string propertyName)
    {
        var name = char.ToLowerInvariant(propertyName[0]) + propertyName.Substring(1);
        return SyntaxFacts.GetKeywordKind(name) != SyntaxKind.None ? "@" + name : name;
    }
}

// arrays lack structural equality, which silently defeats incremental caching.
internal readonly struct EquatableArray<T>(T[] array) : IEquatable<EquatableArray<T>>
    where T : IEquatable<T>
{
    public readonly T[] Array = array;

    public bool Equals(EquatableArray<T> other)
    {
        if (Array.Length != other.Array.Length)
            return false;
        return !Array.Where((t, i) => t.Equals(other.Array[i]) == false).Any();
    }

    public override bool Equals(object? obj) => obj is EquatableArray<T> o && Equals(o);

    public override int GetHashCode()
    {
        if (Array is null)
            return 0;
        unchecked
        {
            return Array.Aggregate(17, (current, item) => current * 31 + item.GetHashCode());
        }
    }
}
