using System;
using System.Linq;
using System.Text;
using Microsoft.CodeAnalysis;
using Microsoft.CodeAnalysis.CSharp;

namespace Nkraft.MvvmEssentials.SourceGenerator;

internal static class NavigationParametersEmitter
{
    public static void Emit(SourceProductionContext spc, ViewModelTarget t)
    {
        if (t.IsPartial == false)
        {
            spc.ReportDiagnostic(Diagnostic.Create(
                Diagnostics.NotPartial,
                t.Location?.ToLocation() ?? Location.None,
                t.ClassName));
            return;
        }

        var invalidNames = t.Parameters.Array
            .Where(p => p.PreferredName is not null && IsValidIdentifier(p.PreferredName) == false)
            .ToArray();

        if (invalidNames.Length > 0)
        {
            foreach (var p in invalidNames)
                spc.ReportDiagnostic(Diagnostic.Create(
                    Diagnostics.InvalidPreferredName,
                    t.Location?.ToLocation() ?? Location.None,
                    p.PreferredName,
                    t.ClassName));
            return;
        }

        var duplicateNames = t.Parameters.Array
            .GroupBy(GetParameterName, StringComparer.Ordinal)
            .Where(g => g.Count() > 1)
            .Select(g => g.Key)
            .ToArray();

        if (duplicateNames.Length > 0)
        {
            foreach (var name in duplicateNames)
                spc.ReportDiagnostic(Diagnostic.Create(
                    Diagnostics.DuplicateParameterName,
                    t.Location?.ToLocation() ?? Location.None,
                    name,
                    t.ClassName));
            return;
        }

        spc.AddSource(BuildHintName(t), BuildSource(t));
    }

    private static string BuildSource(ViewModelTarget t)
    {
        var sb = new StringBuilder();
        sb.AppendLine("// <auto-generated/>");
        sb.AppendLine("#nullable enable");
        if (t.Namespace.Length > 0)
            sb.Append("namespace ").Append(t.Namespace).AppendLine(";").AppendLine();

        sb.Append(t.Accessibility).Append(" partial ").Append(t.TypeKeyword).Append(' ').AppendLine(t.ClassName);
        sb.AppendLine("{");

        var returnType = t.ResultType is null
            ? "global::Nkraft.MvvmEssentials.Services.Pages.PageDestination"
            : $"global::Nkraft.MvvmEssentials.Services.Pages.PopupDestination<{t.ResultType}>";

        sb.Append("    [global::System.CodeDom.Compiler.GeneratedCode(\"").Append(WellKnownNames.GeneratorName).AppendLine("\", \"1.0\")]");
        sb.Append("    public static ").Append(returnType).Append(" With(");
        sb.Append(string.Join(", ", t.Parameters.Array.Select(p => p.IsOptional
            ? $"{ToNullable(p.Type)} {GetParameterName(p)} = default"
            : $"{p.Type} {GetParameterName(p)}"))
        );
        sb.AppendLine(")");
        sb.AppendLine("    {");
        sb.AppendLine("        var __p = new global::Nkraft.MvvmEssentials.Services.NavigationParameters();");

        foreach (var p in t.Parameters.Array)
        {
            var name = GetParameterName(p);
            var guard = p.IsOptional ? $"if ({name} is not null) " : string.Empty;
            sb.AppendLine($"        {guard}__p.Add(\"{p.PropertyName}\", {name});");
        }

        var destinationName = t.ClassName.Replace("ViewModel", t.Suffix);
        sb.AppendLine($"        return new {returnType}(\"{destinationName}\", __p);");
        sb.AppendLine("    }");
        sb.AppendLine("}");
        return sb.ToString();
    }

    private static string BuildHintName(ViewModelTarget t) =>
        (t.Namespace.Length > 0 ? t.Namespace + "." : string.Empty) + t.ClassName + ".NavigationParameters.g.cs";

    private static string ToNullable(string type) =>
        type.EndsWith("?", StringComparison.Ordinal) ? type : type + "?";

    private static string GetParameterName(ViewModelParameter parameter)
    {
        var propertyName = string.IsNullOrEmpty(parameter.PreferredName) ? parameter.PropertyName : parameter.PreferredName!;
        var name = char.ToLowerInvariant(propertyName[0]) + propertyName.Substring(1);
        return SyntaxFacts.GetKeywordKind(name) != SyntaxKind.None ? "@" + name : name;
    }

    private static bool IsValidIdentifier(string name)
    {
        if (string.IsNullOrWhiteSpace(name))
            return false;

        if (SyntaxFacts.IsIdentifierStartCharacter(name[0]) == false)
            return false;

        for (var i = 1; i < name.Length; i++)
            if (SyntaxFacts.IsIdentifierPartCharacter(name[i]) == false)
                return false;

        return true;
    }
}