using System.Collections.Immutable;
using System.Text;
using System.Linq;
using Microsoft.CodeAnalysis;
using Microsoft.CodeAnalysis.CSharp.Syntax;
using Microsoft.CodeAnalysis.Text;
using Location = Microsoft.CodeAnalysis.Location;

namespace Nkraft.MvvmEssentials.SourceGenerator;

[Generator]
public sealed class AppStartupGenerator : IIncrementalGenerator
{
    private const string IAppStartupFullName = "Nkraft.MvvmEssentials.Services.IAppStartup";

    public void Initialize(IncrementalGeneratorInitializationContext context)
    {
        // --- Pipeline 1: user-defined IAppStartup classes ---
        var userStartups = context.SyntaxProvider
            .CreateSyntaxProvider(
                predicate: static (node, _) => node is ClassDeclarationSyntax { BaseList: not null },
                transform: static (ctx, _) => GetIfImplementsIAppStartup(ctx))
            .Where(static x => x is not null)
            .Collect();

        // --- Pipeline 2: MapPage<TPage, TViewModel>(isInitial: true) calls ---
        var initialViewModels = context.SyntaxProvider
            .CreateSyntaxProvider(
                predicate: static (node, _) => node is InvocationExpressionSyntax,
                transform: static (ctx, _) => InitialViewModelDetector.TryGetInitialViewModelFromInvocation(ctx))
            .Where(static x => x is not null)
            .Collect();

        // --- Combine and emit ---
        context.RegisterSourceOutput(
            userStartups.Combine(initialViewModels),
            static (ctx, source) => Execute(ctx, source.Left, source.Right));
    }

    private static INamedTypeSymbol? GetIfImplementsIAppStartup(GeneratorSyntaxContext ctx)
    {
        var classDecl = (ClassDeclarationSyntax)ctx.Node;
        if (ctx.SemanticModel.GetDeclaredSymbol(classDecl) is not INamedTypeSymbol symbol)
            return null;

        return symbol.AllInterfaces.Any(i => i.ToDisplayString() == IAppStartupFullName)
            ? symbol
            : null;
    }

    private static void Execute(
        SourceProductionContext ctx,
        ImmutableArray<INamedTypeSymbol?> userStartups,
        ImmutableArray<string?> initialViewModels)
    {
        var validStartups = userStartups.Where(s => s is not null).ToList();
        var validInitials = initialViewModels.Where(s => s is not null).ToList();

        // MVE002 — more than one IAppStartup
        if (validStartups.Count > 1)
        {
            var names = string.Join(", ", validStartups.Select(s => s!.Name));
            ctx.ReportDiagnostic(Diagnostic.Create(
                Diagnostics.MultipleStartupsDefined, Location.None, names));
            return;
        }

        // MVE001 — nothing defined at all
        if (validStartups.Count == 0 && validInitials.Count == 0)
        {
            ctx.ReportDiagnostic(Diagnostic.Create(
                Diagnostics.NoStartupDefined, Location.None));
            ctx.AddSource("AppStartup.Registration.g.cs",
                SourceText.From(GenerateNoOpRegistration(), Encoding.UTF8));
            return;
        }

        if (validStartups.Count == 1)
        {
            // User-defined IAppStartup — just wire it up
            ctx.AddSource("AppStartup.Registration.g.cs",
                SourceText.From(
                    GenerateUserStartupRegistration(validStartups[0]!),
                    Encoding.UTF8));
        }
        else
        {
            // No IAppStartup found — generate default from isInitial: true
            if (validInitials.Count > 1)
            {
                ctx.ReportDiagnostic(Diagnostic.Create(
                    Diagnostics.MultipleStartupsDefined, Location.None,
                    string.Join(", ", validInitials)));
                return;
            }

            var initialVmFullName = validInitials[0]!;

            ctx.AddSource("AppStartup.Default.g.cs",
                SourceText.From(GenerateDefaultStartup(initialVmFullName), Encoding.UTF8));

            ctx.AddSource("AppStartup.Registration.g.cs",
                SourceText.From(GenerateDefaultStartupRegistration(), Encoding.UTF8));
        }
    }

    // -------------------------------------------------------------------------
    // Code templates
    // -------------------------------------------------------------------------

    private static string GenerateUserStartupRegistration(INamedTypeSymbol startup)
    {
        var fullName = startup.ToDisplayString();
        return $$"""
            // <auto-generated/>
            // Detected user-defined IAppStartup: {{fullName}}
            #nullable enable

            using Microsoft.Extensions.DependencyInjection;
            using Nkraft.MvvmEssentials.Services;

            namespace Nkraft.MvvmEssentials;

            internal static class AppStartupRegistrationExtensions
            {
                internal static IServiceCollection AddDiscoveredAppStartup(this IServiceCollection services)
                {
                    services.AddTransient<IAppStartup, {{fullName}}>();
                    return services;
                }
            }
            """;
    }

    private static string GenerateDefaultStartup(string initialViewModelFullName)
    {
        return $$"""
            // <auto-generated/>
            // Default IAppStartup generated from MapPage<_, {{initialViewModelFullName}}>(isInitial: true)
            #nullable enable

            using System.Threading.Tasks;
            using Nkraft.MvvmEssentials.Extensions;
            using Nkraft.MvvmEssentials.Services;

            namespace Nkraft.MvvmEssentials;

            internal sealed class GeneratedAppStartup : IAppStartup
            {
                private readonly INavigationService _navigationService;

                public GeneratedAppStartup(INavigationService navigationService)
                {
                    _navigationService = navigationService;
                }

                public async Task OnInitializedAsync()
                {
                    await _navigationService
                        .Absolute(withNavigation: false)
                        .Push(typeof({{initialViewModelFullName}}))
                        .NavigateAsync();
                }
            }
            """;
    }

    private static string GenerateDefaultStartupRegistration()
    {
        return """
            // <auto-generated/>
            #nullable enable

            using Microsoft.Extensions.DependencyInjection;
            using Nkraft.MvvmEssentials.Services;

            namespace Nkraft.MvvmEssentials;

            internal static class AppStartupRegistrationExtensions
            {
                internal static IServiceCollection AddDiscoveredAppStartup(this IServiceCollection services)
                {
                    services.AddTransient<IAppStartup, GeneratedAppStartup>();
                    return services;
                }
            }
            """;
    }

    private static string GenerateNoOpRegistration()
    {
        return """
            // <auto-generated/>
            #nullable enable

            using Microsoft.Extensions.DependencyInjection;

            namespace Nkraft.MvvmEssentials;

            internal static class AppStartupRegistrationExtensions
            {
                internal static IServiceCollection AddDiscoveredAppStartup(this IServiceCollection services)
                    => services; // MVE001: no startup defined
            }
            """;
    }
}