name: .NET

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4

    - name: Clone CrossUtility
      run: git clone https://github.com/mr5z/CrossUtility ../CrossUtility

    - name: Setup .NET
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: 9.0.x

    - name: Restore dependencies
      run: dotnet restore MvvmEssentials.sln

    - name: Build
      run: dotnet build MvvmEssentials.sln --no-restore --configuration Release

    - name: Test
      run: dotnet test MvvmEssentials.sln --no-restore --configuration Release --logger "console;verbosity=detailed"
