name: .NET

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: Setup .NET
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: 9.0.x

    - name: Clone dependency (CrossUtility)
      # The key part: move one directory up before cloning
      run: |
        cd ..
        git clone https://github.com/mr5z/CrossUtility

    - name: Restore dependencies
      run: dotnet restore Nkraft.MvvmEssentials.csproj

    - name: Build
      run: dotnet build Nkraft.MvvmEssentials.csproj --no-restore --configuration Release
